services:
  dns-tailscale-1:
    build: .
    container_name: dns-tailscale-1
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - DOMAINS=.overridedomain.local:100.77.35.105,override1.example.com:100.83.17.42
      - UPSTREAM_DNS=8.8.8.8 8.8.4.4
      - HEALTHCHECK_DOMAIN=google.com
      - MODE=master
      - MASTER_URL=
      - NODE_NAME=dns-server-1
      - INGEST_SECRET=my_super_secret_token
    ports:
      - "127.0.0.1:${PORT:-35353}:35353"
    volumes:
      - ./history:/var/lib/tailscale-dnsrewrite
      - ./tailscale:/var/lib/tailscale
    sysctls:
      - net.core.somaxconn=1024
      - net.ipv4.tcp_fastopen=3
    restart: unless-stopped
